name: [TEST] Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.ACR_REPO_NAME }}:${{ github.sha }} .

    # Conditionally push the image based on environment
    - name: Conditionally Push Image to ACR
      if: github.event_name != 'pull_request' && github.event.pull_request == null && inputs.push == 'true'
      run: |
        echo "Skipping image push as 'push' is set to false."
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.ACR_REPO_NAME }}:${{ github.sha }}

    - name: Azure logout
      run: az logout
