apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ cookiecutter.project_name }}
  description: {{ cookiecutter.description }}
spec:
  type: service
  owner: {{ cookiecutter.owner }}
  lifecycle: production # experimental
